#Selection Tool
FavFarm:
Tool:
#The Item Used For Catching Animals For Farms
Catcher:
  Material: "SNOW_BALL"
  DisplayName: '&3Animal Catcher'
#Amount Of Catchers A Player Starts With
  Amount: 5
#The Selection For Favoutire Farms Creation
Selector:
  Material: "BLAZE_ROD"
  DisplayName: '&6Farm Selector'
Delays:
#How Long Until A Player Can Create Another Farm In Seconds
  FarmCreation: 60
#How Long Until A Player Can Recieve More Catchers In Seconds
  CatcherCooldown: 60
#How Long A Player Has Received An Increase Catch Rate in Seconds
  IncreasedRateTime: 60
#If A Farm Commands Have A Cooldown And For How Long In Seconds
  CommandCooldown:
    Enabled: true
    Time: 3
#Player Enhancemnts
Enhancement:
#Catch Rate Will Be Turned To A Percentage Don't Add A '%' Sign After Number
  CatchRateIncrease: 25
#Blocks A Player Starts With and Increases By Per Level
Size:
#Amount Of Blocks A Player Starts With
  Amount: 150
#Increment Amount Per Level
  Increment: 10
#Defualt Farm Animal Type/Style Change Usages A Player Starts With
Usages:
#Defualt Amount Of Tames A Player Receives
  Tame: 2
#Defualt Amount Of Sheep Fur Reset Usages A Player Receives
  FurReset: 3
#Defualt Amount Of Ocelot/Horse Style Change Usages A Player Receives
  StyleSets: 4
#Defualt Catch Rate For Each Animal, Max 100
CatchRate:
  Chicken: 78.6
  Cow: 64.6
  Horse: 31.4
  Ocelot: 28.3
  Pig: 82.9
  PolarBear: 20.9
  Rabbit: 18.4
  Sheep: 72.9
  Wolf: 36.6
#Experience Gained For Capturing In A Range
Experience:
  Most:
    Chicken: 18
    Cow: 19
    Pig: 17
    Sheep: 17
    Wolf: 25
    Horse: 29
    Ocelot: 31
    PolarBear: 45
    Rabbit: 49
  Least:
    Chicken: 2
    Cow: 3
    Pig: 1
    Sheep: 4
    Wolf: 6
    Horse: 8
    Ocelot: 11
    PolarBear: 14
    Rabbit: 17