name: FavouriteFarms
version: 1.0.0
description: Extensively Created Farming Plugin For Minecraft Servers
softdepend: [WorldGuard, WorldEdit, GriefPrevention]
 
author: Azewilous
website: http://azewilous.github.io
 
main: io.github.favfarms.FavFarms
database: false

commands:
  farm:
    description: Favourite Farms Base Command
    usage: /farm

permissions:
  favfarms.*:
    description: Gives Access To All Permissions For Favourite Farms
  favfarms.farm:
    description: Displays Plugin Help
    default: true
  favfarms.reload:
    description: Access To Reload Command
  favfarms.tool.self:
    description: Access To Farm Creation Tool
  favfarms.tool.other:
    description: Access To Give Another Player A Creation Tool
  favfarms.show.self:
    description: Access To Highlight Farm Area For Player
  favfarms.show.other:
    description: Access To See Another Players Farm Area
  favfarms.farms.create:
    description: Access To Create A Farm
  favfarms.create.other:
    description: Access To Create A Farm For Another Player
  favfarms.farms.remove:
    description: Access To Remove A Farm
  favfarms.info.self:
    description: Access To Get Farm Info For Self
  favfarms.info.other:
    description: Access To Get Farm Info For Others
  favfarms.catcher.self:
    description: Access To Obtain Catch Tool
  favfarms.catcher.other:
    description: Access To Give Others A Catch Tool
  favfarms.set.spawn:
    description: Access To Set Farm Spawn
  favfarms.inv.self:
    description: Open Farm Inventory For Self
  favfarms.inv.other:
    description: Open Farm Invneotry Of Others
  favfarms.farm.animals:
    description: Access To See Animals A Player Owns
  favfarms.bypass.area:
    description: Access To Create Farm On Top of Claims/Regions
  favfarms.farms.multiple:
    description: Access To Use Multiple Farms Command
  favfarms.farms.multiple.:
    description: Amount Of Farms A Player Can Have
  favfarms.farm.multiple.unlimited:
    description: Access To Create An Unlimited Amount Of Farms